### ISSUE TITLE
Return "deep variable" working incorrect

### ISSUE THREAD

**Issue by phambinh217** [kalimatas/php-liquid#101]
I have issue
```
{{ settings.my_key }}
```
My mean is echo property `my_key` in `settings` object.
If `my_key` is exists, it return well, but when `my_key` no exists, it return all property in settings object. I think it have to return `null`

Please check.
Sorry my bad english

**Comment by sanmai** [comment]
How does it look like?

Could you give a code sample to reproduce this problem?

**Comment by phambinh217** [comment]
I have a object called `settings`, and it have many properties, when I want to call a property, I do bellow
```
settings.the_property_i_need
```
Ex: `settings.home_title` return a meta title of home a page.
But above is the case well.

If I use a property and it not exists in `settings` object, it must return null (or same). But now it return a object `settings`. same case
```
{{ settings }}
```

**Comment by sanmai** [comment]
Oh, I think I understand what is the problem.

**Comment by phambinh217** [comment]
Thank you

**Comment by sanmai** [comment]
I can't reproduce this issue either.
```php
$template = new \Liquid\Template();
$template->parse("my_key={{ settings.my_key }}; invalid={{ settings.invalid }}");
echo $template->render([
	'settings' => [
		'my_key' => 'foo',
	],
]);
```
Outputs:
```
my_key=foo; invalid=
```

1. Are you sure you're using this library?
2. Are you using most recent version?

**Comment by phambinh217** [comment]
I am sure using this lib and it is most recent version, because I cloned it yesterday
But if settings if a object, like bellow
![image](https://user-images.githubusercontent.com/15150529/37747889-e3cc5dcc-2db3-11e8-9ccb-70f05557f3c2.png)

and result
![image](https://user-images.githubusercontent.com/15150529/37747898-f1f38ee8-2db3-11e8-99d3-065e4450cba4.png)

Now, i fix it by change setting object to array like
```
$settings = (array) new Settings();
```

**Comment by sanmai** [comment]
Please give me a code sample I can run that demonstrates this problem. Thank you.

**Comment by sanmai** [comment]
So I made it return null for missing properties, and nothing else breaks so far.

Thank you for making this library better. I'll make a new release after CI would pass.

**Comment by phambinh217** [comment]
Thank you
