### ISSUE TITLE
Render item in array not woking

### ISSUE THREAD

**Issue by phambinh217** [kalimatas/php-liquid#102]
Dear,
I am again :)
I have array like bellow

```
images = array('image 1', 'image 2', 'image3');
```

When I use {{ images.size }}, it return 3. OK it true
But when I use {{ images[1 }} to display a item at index 1, it not woking, it return null or empty string

Please check

**Comment by sanmai** [comment]
I can't reproduce this issue:
```php
$template = new \Liquid\Template();
$template->parse("size: {{ images | size }}\nimage: {{ images[1] }}");
echo $template->render([
	'images' => ['image1', 'image2', 'image3'],
]);
```
Outputs expected:
```
size: 3
image: image2
```
