### ISSUE TITLE
When use '__toString()', 'toArray()', 'toLiquid()' methods?

### ISSUE THREAD

**Issue by phambinh217** [kalimatas/php-liquid#104]
I read on `Context` class, I see some case we use `__toString()`, `toArray()`, `toLiquid()`, but i don't know how to use exactly.
Can you give a doc or explain

**Comment by sanmai** [comment]
Use `__toString()` like you would usually use. There's nothing special about it.

Don't use `toArray()`, `toLiquid()` unless absolutely necessarily. They're mostly for backward compatibility.
