### ISSUE TITLE
Get content TagBlock

### ISSUE THREAD

**Issue by maicolbruski** [kalimatas/php-liquid#106]
Hi,

How to get a content of a block, for render into a loop and return a list of initial content?
example:
```
{% posts limit: 2 offset: 0 %}
            <li>teste</li>
            <li>{{ post.name }}</li>
            <li>final</li>
{% endposts %}
```

Im using a class 

```class TagPosts extends AbstractBlock {}```

Tks

**Comment by sanmai** [comment]
Would you care to provide a more complete example?
