### ISSUE TITLE
HTML filters tag is not work

### ISSUE THREAD

**Issue by phamvansy** [kalimatas/php-liquid#107]
I use img_tag, script_tag, stylesheet_tag not work
Examples:
`{{ 'shop.css' | asset_url | stylesheet_tag }}`

**Comment by asacarter** [comment]
You have to create your own filters.

https://github.com/harrydeluxe/php-liquid/wiki/Liquid-for-programmers

**Comment by phamvansy** [comment]
My output:
`&lt;link href=&quot;/theme/default/stylesheets/master.css&quot; media=&quot;sreen&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;`
It is encode html

**Comment by phamvansy** [comment]
Yes, i resolve this problems, by set false ESCAPE_BY_DEFAULT
`Liquid::set('ESCAPE_BY_DEFAULT', false);`
Thank you so much bro

**Comment by sanmai** [comment]
That’s not a very good idea. You open yourself to various variants of XSS.

Much better would be to use the “raw” filter:

     {{ plain-html | raw }}

**Comment by phamvansy** [comment]
Can i add raw function in filter class?

**Comment by sanmai** [comment]
I think you can, but let me check that.

You can always be explicit though.

**Comment by sanmai** [comment]
No just use ‘raw’ and be done

    {{ 'shop.css' | asset_url | stylesheet_tag | raw }}

**Comment by phamvansy** [comment]
yes, thanks you so much
