### ISSUE TITLE
How to parse Timber template in Laravel application

### ISSUE THREAD

**Issue by mtasuandi** [kalimatas/php-liquid#11]
Hi,

I'm trying to parse Timber template framework provided by Shopify, the goal is to make the Laravel application able to render the Timber template using this Liquid parser.

I'm not familiar with Timber before, but from what I read from the documentation. The theme.liquid file is the main template file where the other parts of the template are included from this file.

So, I just try to parse the theme.liquid file but it gave me an error "No file system".

Here's my controller
```php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Liquid\Template;

class TemplateParser extends Controller
{
  public function liquid()
  {
    $template_path = storage_path() . DIRECTORY_SEPARATOR . 'themes/timber' . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR;
    $template_string = file_get_contents($template_path . 'theme.liquid');
    
    $template = new Template();
    $template->parse($template_string);
    $replacer = [];
    return $template->render($replacer);
  }
}
```
I'm not sure what the error means and how to solve it. Any ideas?

Teguh

**Comment by kalimatas** [comment]
Hi!

Can you show the context of you `theme.liquid` file?

**Comment by mtasuandi** [comment]
I was working on one project before, and it was Shopify Theme Builder. I think i can use this parser to get "live preview" from the liquid file but suddenly i figure out if the Timber template can't be previewed from PHP because it contains some of Ruby code.
