### ISSUE TITLE
Content injection from $_SERVER

### ISSUE THREAD

**Issue by sanmai** [kalimatas/php-liquid#114]
Issue similar to #22. It is not as unsafe, but still can cause unintended leaks.

See for details: 
https://github.com/harrydeluxe/php-liquid/issues/54

It is hard to tell why there's a need to pass $_SERVER in the context, but I guess we can safely pass a some subset of it.

**Comment by zemaj** [comment]
Oof that's not great. I think $_SERVER should be removed entirely from the default environment. It's counterintuitive that data in $_SERVER would be automatically exposed to templates. As pointed out in #harrydeluxe#54 passwords could easily be exposed this way.

Presumably this was added to make variables like HTTP_USER_AGENT available to templates, but the risk of exposing secure server data should outweigh this convenience. I can't see any functionality that is affected by removing $_SERVER from the initialization of environments.

**Comment by sanmai** [comment]
Thanks for reminding about this issue. Indeed, exposing things like `AWS_SECRET_ACCESS_KEY` can have very unpleasant consequences.
