### ISSUE TITLE
If you use filter without required argument then php throw `Type Error`.

### ISSUE THREAD

**Issue by PATROMO** [kalimatas/php-liquid#126]
Try: 
```
{{"now"|date }} or {{ 4 | plus }}
```

and you get:
```
Type error: Too few arguments to function Liquid\StandardFilters::date(), 1 passed and exactly 2 expected 
```

An LiquidException should be thrown.

**Comment by sanmai** [comment]
That is in fact correct. The date filter requires a format.

https://shopify.github.io/liquid/filters/date/

**Comment by PATROMO** [comment]
I know, but `LiquidException` should be thrown and not a PHP Error.

**Comment by sanmai** [comment]
Fair.

**Comment by PATROMO** [comment]
I will try to create a PR for it. :)

**Comment by sanmai** [comment]
Consider catching TypeError somewhere up the stack, and rethrowing a `LiquidException` with that `TypeError` set as a previous exception. That'll be a solution for all other similar cases too.
