### ISSUE TITLE
Unkown tag continue

### ISSUE THREAD

**Issue by kvz** [kalimatas/php-liquid#13]
It seems continue is not supported? Use case:

```
  {% for plan in site.data.public_plans %}
    {% if plan[1].slug == "sandbox" and showSandboxPlan == false %}
      {% continue %}
    {% endif %}
  {% endfor %}
```

**Comment by NathanBaulch** [comment]
Implemented [here](https://github.com/NathanBaulch/php-liquid/commit/12db26ce358127be8cd469b80fc4e06bfaa7c4b6).

**Comment by kvz** [comment]
🎉

**Comment by sanmai** [comment]
Should that be closed before #25 merged or whatnot? Think not.

**Comment by NathanBaulch** [comment]
I should probably break my various improvements into separate branches and pull requests instead of that one catch-all PR.

**Comment by kvz** [comment]
Right sorry
