### ISSUE TITLE
Bug in Whitespace control in combination with If and greater/ smaller than.

### ISSUE THREAD

**Issue by PATROMO** [kalimatas/php-liquid#138]
An example from https://shopify.github.io/liquid/basics/whitespace/ 

```
{%- assign username = "John G. Chalmers-Smith" -%}
{%- if username and username.size > 10 -%}
  Wow, {{ username }}, you have a long name!
{%- else -%}
  Hello there!
{%- endif -%}
```

Generates the output: `Hello there!`

if I remove the whitespace control, then I get `Wow, John G. Chalmers-Smith, you have a long name!`

**Comment by sanmai** [comment]
Thanks for the report. Do you think you can manage a PR to fix this issue?

**Comment by PATROMO** [comment]
@sanmai II'll try it these days. At first I just wanted to share the problem.

**Comment by PATROMO** [comment]
@sanmai Sorry, I checked it wrong. There is no bug.
