### ISSUE TITLE
Assign variable value

### ISSUE THREAD

**Issue by rusrocket** [kalimatas/php-liquid#146]
I'm trying to achieve the same functionality as Shopify "section" has. ( https://shopify.dev/docs/themes/sections )
This section includes files as templates, has own variables like {{ section.settings.blablabla }} and has tags like {% schema %} ...here json string with settings... {% endschema %} 

I created section tag based on AbstractTag, so now part of template is being included into main template.

Also I created SCHEMA tag based on AbstractBlock. In this Schema Tag I parse this json string with settings to json object. I need somehow to pass this newly created json object (or array) to template as variable value. The question is: How I can pass variable value to template? ( Is this something like $context->set(). ??? ) Could you please guide me, and give some code example. And if not so complicated, could please give schematically flow of library, like: Parser get files ->go to Context -> Context check Variables in Variables -> etc. Because now it is not so clear 

`<?php namespace Liquid\Tag;

 use Liquid\AbstractBlock;
 use Liquid\Decision;
 use Liquid\Context;
 use Liquid\Exception\ParseException;
 use Liquid\Liquid;
 use Liquid\FileSystem;
 use Liquid\Regexp;
 use Liquid\Variable;

class TagSchema extends AbstractBlock
{

	protected $blocks = array();

	public function __construct($markup, array &$tokens, FileSystem $fileSystem = null)
	{
	
		array_push($this->blocks, array(&$this->nodelist));

		parent::__construct($markup, $tokens, $fileSystem);
	}

	public function render(Context $context)
	{

		if(isset($this->blocks[0]) && isset($this->blocks[0][0]) && isset($this->blocks[0][0][0])){

			$json = $this->blocks[0][0][0];
			$js = json_decode($json,true);

			// HERE IS THE QUESTION: HOW TO PASS VARIABLE TO TEMPLATE, IS IT CORRECT?
			
			$from = new Variable($json);
			$output = $from->render($context);
			$context->set("section", $output, true);

		}

	}
}

`

**Comment by sanmai** [comment]
Do you think you can accompany your question with relevant code? As in a PR.

**Comment by rusrocket** [comment]
> Do you think you can accompany your question with relevant code? As in a PR.

Yes, I updated

**Comment by rusrocket** [comment]
I found a way to set variable=value using:

`$context->set("var_name", "var_value", true);`

but it isn't rendered in template using {{ var_name }}

**Comment by rusrocket** [comment]
solved
