### ISSUE TITLE
Increment tag not starting at 0

### ISSUE THREAD

**Issue by brenoalvs** [kalimatas/php-liquid#149]
The original Liquid implementation for `increment` tag starts from 0.

It seems that the library default is -1.
https://github.com/kalimatas/php-liquid/blob/master/src/Liquid/Tag/TagIncrement.php#L75

Can I fix this?

**Comment by sanmai** [comment]
I'm sure I can review a PR if you could manage to make it. And, well, if you could provide reference to the original implementation, that would be best.

**Comment by brenoalvs** [comment]
@sanmai https://shopify.github.io/liquid/tags/variable/#increment
> Creates and outputs a new number variable with initial value 0. On subsequent calls, it increases its value by one and outputs the new value.

**Comment by brenoalvs** [comment]
@sanmai I'm sorry, it seems that it's working properly.
The issue is with another library.
