### ISSUE TITLE
LocalFileSystem bad exception message

### ISSUE THREAD

**Issue by JoshWillik** [kalimatas/php-liquid#15]
Let's say you get a template name wrong. This can happen for any number of reasons. 
In my case, I didn't realize there was a default `_` prefixing includes.

You initialize Liquid with 

``` php
$renderer = new \Liquid\Template(__DIR__ . '/templates/');
$renderer->parse(file_get_contents(__DIR__ . '/templates/'));
echo $renderer->render([]);
```

The template looks like this:

``` twig
{% include 'header' %}
Hello
{% include 'footer' %}
```

Inside [LocalFileSystem](https://github.com/kalimatas/php-liquid/blob/master/src/Liquid/LocalFileSystem.php#L78) `$fullPath` is set to `/src/project/templates/_header.liquid`, which does not exist.

The following exception is then thrown:

```
Details
Type: Liquid\LiquidException
Message: Illegal template path ''
File: C:\src\project\vendor\liquid\liquid\src\Liquid\LocalFileSystem.php
Line: 84
```

This isn't really that helpful. [PHP's docs on realpath](http://php.net/manual/en/function.realpath.php) state that for a missing file, `realpath` will return false. So as far as I can tell, there is no case when [the current thrown exception](https://github.com/kalimatas/php-liquid/blob/master/src/Liquid/LocalFileSystem.php#L78) will give a useful error message.

Is there a reason that `realpath` is being called here?

**Comment by steven-parker** [comment]
The above issue does exist. When you include a file the filename must be prefixed by an underscore. The error of "Illegal template path ''" is not helpful at all.

**Comment by sanmai** [comment]
This is customary for Liquid to prepend a template name with an underscore, and append `.liquid`. E.g. with these additions in place, if you're moving from Ruby's Liquid, you can expect your templates work as before.

If you want to turn off this compatible behavior, you can do it with:

    Liquid::set('INCLUDE_ALLOW_EXT', true);

**Comment by sanmai** [comment]
I'll keep this open until we could document this behavior.

**Comment by JoshWillik** [comment]
The issue isn't about default underscores. The underscores are fine (though some docs on that would be nice).

The real problem is that when the file doesn't exist, the error message is completely unhelpful.
I would expect an error like:
```
Template at _foobar.liquid does not exist
```
and not the current error:
```
Illegal template path ''
```

**Comment by JoshWillik** [comment]
Disclaimer:
I haven't actually used php-liquid in over a year.
If the bad error message is no longer the case, feel free to close

**Comment by sanmai** [comment]
I think I've done just that in some of recent commits, but I'll check just for sure.

**Comment by sanmai** [comment]
Indeed it'll tell you something akin to this:

    File not found: /full/path/to/templates/no_such_file_exists.tpl

**Comment by sanmai** [comment]
Keeping it open as a documentation issue.
