### ISSUE TITLE
Base case for rendering templates is a bid finicky.

### ISSUE THREAD

**Issue by JoshWillik** [kalimatas/php-liquid#16]
It strikes me that the usability of Liquid doesn't really compare all that well against, say, [Mustache](https://github.com/bobthecow/mustache.php).

Compare the following examples:

**Mustache**

The base directory is defined once:

``` php
$renderer = new Mustache_Engine(array(
    'loader' => new Mustache_Loader_FilesystemLoader(__DIR__ . '/views'),
));
echo $renderer->render('home');
```

**Liquid**

Even though we pass the base directory into the constructor, we're still left manually loading the template a second time.

``` php
$renderer = new \Liquid\Template(__DIR__ . '/templates/');
$renderer->parse(file_get_contents(__DIR__ . '/templates/home'));
echo $renderer->render();
```

It feels like there must be a better way to handle this.

How do you feel about a code interface that looks something like the following?

``` php
$renderer = new \Liquid\Liquid(array(
    'filesystem' => new \Liquid\LocalFileSystem(__DIR__ . '/templates')
));
echo $renderer->render('home', $page_data);
```

**Comment by sanmai** [comment]
Liquid::set('INCLUDE_PREFIX', '');
    Liquid::set('INCLUDE_ALLOW_EXT', true);
    
    $template = new Template(__DIR__ . '/templates');
    echo $template->parseFile('home')->render();

Will parse and render `templates/home.liquid`
