### ISSUE TITLE
Can I use the % operator?

### ISSUE THREAD

**Issue by vrgenl** [kalimatas/php-liquid#160]
Hi!

I have an issue what I cant seem to solve. I have a for loop and I want to echo something every 4th iteration of the for loop.

Normaly I would something like index % 4 === 1 that echo that thing but this is not working.

Anyone know how I can solve this?

**Comment by schmoove** [comment]
You want the `modulo` filter as documented in the original Ruby implementation:

https://shopify.github.io/liquid/filters/modulo/
