### ISSUE TITLE
Deprecated Functionality: Function strftime() is deprecated 

### ISSUE THREAD

**Issue by birdman002** [kalimatas/php-liquid#170]
We have a magento 2 function that calls your package. We are upgrading to PHP8.1 and the function strftime is deprecated

Full error message 
`Deprecated Functionality: Function strftime() is deprecated in /app/vendor/liquid/liquid/src/Liquid/StandardFilters.php on line 81`

Do you know of a way to use something different than strftime.

Thanks!

**Comment by sanmai** [comment]
Feel free to make a PR to fix this issue [with a replacement](https://www.php.net/manual/en/function.strftime.php).

**Comment by SachinBahukhandi** [comment]
Are any active PR's for this issue? Also, any steps to replicate this issue?

**Comment by sanmai** [comment]
It looks like it is up for grabs.

**Comment by SachinBahukhandi** [comment]
> It looks like it is up for grabs.

Any idea on how to replicate this issue?

**Comment by schmoove** [comment]
I have a PR open here:

https://github.com/kalimatas/php-liquid/pull/175
