### ISSUE TITLE
Separate location for CustomFilters and custom Tags?

### ISSUE THREAD

**Issue by schmoove** [kalimatas/php-liquid#35]
Would it be better to have the CustomFilters.php file and any user-added custom tags placed in a location outside the composer package? 

Each time we composer update, it overwrites our CustomFilters.php :(

**Comment by sanmai** [comment]
So did you find a way to do it?

**Comment by schmoove** [comment]
To be honest I closed because I thought there must be an obvious solution out there related to composer packages. 

Apparently it's best to either clone our own copy of the repo, or extend the base classes? 
Certainly open to any suggestions though - so far we have added our own Custom Filters and Tags, and it would be much easier to not have to maintain the package each time we update it.

**Comment by sanmai** [comment]
If you could extend the base classes and accomplish the task, then you should definitely do this.

Entirely different question if you couldn't just subclass something and make it work.

**Comment by schmoove** [comment]
I asked around and now understand the best practice needed here - thanks!
