### ISSUE TITLE
Multiple forks

### ISSUE THREAD

**Issue by ryanmitchell** [kalimatas/php-liquid#7]
Hey

I am prepared to do a bit of work to merge this fork in with the mutliple other forks and make it the new 'master' fork (as harrydeluxe's is now clearly dead).

If I do this are you prepared to start accepting PR's? Or should I merge everything into a different fork entirely?

Ryan

**Comment by kalimatas** [comment]
Hi, Ryan

What do you mean by 'master fork'?
I'll try to find some time and merge new pull requests.

**Comment by ryanmitchell** [comment]
Hi

I guess I mean making your fork become the de-facto default, with all of the changes from the other fork included.

Its very fragmented at the minute and it would be better to have one repo that everyone contributes to and PR’s get checked and approved in.

Ryan

**Comment by kalimatas** [comment]
Agree. I'm ready to accept and review pull requests. I'll try to do my best :)

**Comment by ryanmitchell** [comment]
Great! I'll spend some time compiling changes over the next few days and open them as PRs

We use this library pretty extensively so I'm keen to ensure it stays alive!
