### ISSUE TITLE
Different exceptions should be thrown depending on the case.

### ISSUE THREAD

**Issue by jfoucher** [kalimatas/php-liquid#74]
At the moment, every exception is a `Liquid\LiquidException` which makes it difficult to only catch some types of problems. I would like to refactor so that for example a parse error will throw a `Liquid\Exception\ParseException` and an unclosed tag error a `Liquid\Exception\UnclosedTagException`. They would of course all extend `Liquid\LiquidException` to make it possible to catch all Liquid exceptions, like it is now.
What do you think?

**Comment by jfoucher** [comment]
We should also think about the granularity of exception, i.e. do un unclosed tag and an unknown tag throw the same exception, or a different one? Looking forward to hearing your opinion on this as well.

**Comment by sanmai** [comment]
In other projects I do like you propose every time I need to throw an exception. If you want to make a PR with this, please go ahead.
