### ISSUE TITLE
Unless doesn't work in for loops with forloop.first or forloop.last

### ISSUE THREAD

**Issue by jfoucher** [kalimatas/php-liquid#80]
This test fails for example : 

```
    public function testForAndUnless()
    {
        $assigns = array('array' => array(1, 2, 3));
        $this->assertTemplateResult('     yay ', '{%for item in array%} {% unless forloop.last %}yay{% endunless %} {%endfor%}', $assigns);
    }
```

**Comment by jfoucher** [comment]
Test result is as follows:

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'     yay '
+'      '
```

**Comment by sanmai** [comment]
Nice find, thanks!

I saw you trying to remake Jekyll with PHP. If you think we need to change anything else in Liquid, please make a PR.

E.g. I would love to see at least some of the Liquid filters from Jekyll.

**Comment by jfoucher** [comment]
Hi @sanmai I have made some extensions to liquid, yes, some filters and so on but that are not in the core version of (ruby) Liquid but extensions specific to Jekyll, that's why I didn't send any pull requests with them. You can view my additions here: https://github.com/jfoucher/stati/tree/master/src/Liquid
Feel free to ask me for some pull requests or pick and choose what you want.

**Comment by sanmai** [comment]
Great. Looking at [the themes report](https://stati.jfoucher.com/report.html) I see that some themes fail with "Implicit rendering of arrays not supported" error. Could you tell how these themes work in the stock Jekyll? How are such errors handled there?

**Comment by jfoucher** [comment]
Yes that is the next issue I will be tackling. I'll let you know about my findings.
