### ISSUE TITLE
Error {% include 'test-include' %}

### ISSUE THREAD

**Issue by maicolbruski** [kalimatas/php-liquid#85]
Hi,

When I add a include with '-' Liquid returns error:
**Illegal template name 'test-include'**

In Class Liquid\FIleSystem\Local exists a rule in function `fullPath()` in line **78**:
new Regexp('/^[^.\/][a-zA-Z0-9_\/]+$/');

But if i change to **new Regexp('/^[^.\/][a-zA-Z0-9_\-\/]+$/');** works perfectly.

This is correct, or have another config for this?

**Comment by maicolbruski** [comment]
The composer downloading 1.4 version..
In version dev-master is works perfect!
Tks.

**Comment by sanmai** [comment]
I'll leave it open until I can make a new release.
