### ISSUE TITLE
Filter with after assign

### ISSUE THREAD

**Issue by maicolbruski** [kalimatas/php-liquid#86]
Hi,

Im try to use custom filter after assign, but **object of assign** returns empty.
for example:

```
{% assign pro = content_products[item.settings.product] %}
{{ pro | microdata: 'product' }}
<h3>{{ pro.name }}</h3>
```

In filter **microdata** returns empty;
In tag **h3** show name of product...

This is correct, exists another alternative for this?
Tks!

**Comment by maicolbruski** [comment]
Resolved!

**Comment by sanmai** [comment]
What was wrong there in the end?

**Comment by maicolbruski** [comment]
it was my mistake, I was with a die() wrong...
