### ISSUE TITLE
Capture tag in if statment doesn't work

### ISSUE THREAD

**Issue by afigienas** [kalimatas/php-liquid#90]
Hi, I have an issue: when I use "capture" tag in "if" condition, it doesn't work.

```
{% assign my_variable = 'test 0' %}

{% if true %}
  {% capture my_variable %}'test 1'{% endcapture %}
{% else %}
  {% capture my_variable%}'test 2'{% endcapture %}
{% endif %}

{{ my_variable }} // 'test 0'

```

**Comment by sanmai** [comment]
Indeed `capture` won't work inside an `if` where an `assign` would work just fine.

**Comment by sanmai** [comment]
Under Jekyll this example works as you expect. Hence it's a confirmed bug.
