### ISSUE TITLE
endpaginate does not end pagination

### ISSUE THREAD

**Issue by asacarter** [kalimatas/php-liquid#93]
Ending pagination still paginates outside of the paginate block.

For example in a blog where you want to paginate posts but also have a sidebar that reuses the same data. 

`{% paginate blog.articles by 4 %}
	{% for article in blog.articles %}
		{{ article.title }}
	{% endfor %}
{% endpaginate %}

{% for article in blog.articles %}
	{{ article.title }}
{% endfor %}`

**Comment by edwardoka** [comment]
Confirmed with following test.

```
	public function testPaginationForRepeatedCalls()
	{
		$text = '{% paginate articles by 2 %}{% for article in articles %}{{ article.title }},{% endfor %}{% endpaginate %} {% for article in articles %}{{ article.title }},{% endfor %}';

		$expected = '1,2, 1,2,3,';


		$this->assertTemplateResult($expected, $text, array(
			'page' => 1,
			'articles' => array(array('title' => 1),array('title' => 2),array('title' => 3))
		));
	}

```
Expected: '1,2, 1,2,3,'
Actual: '1,2, 1,2,'

**Comment by sanmai** [comment]
@edwardoka that's super cool that you made a test case! I'm going to fix this in the master within an hour.

**Comment by edwardoka** [comment]
@sanmai Sweet, I was looking at doing something like a special collection name e.g. article__paginated, and substituting tokens referencing the original in the constructor, but if you've got a solution then I'll hold off

**Comment by sanmai** [comment]
Let's just wait for CI for #95 to pass.

**Comment by sanmai** [comment]
1.4.6 is out. Thanks for the work, y'all.
